services:
  parhelion:
    image: wheelercj/parhelion:latest
    container_name: parhelion
    depends_on:
      - parhelion_db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    env_file: .env
    environment:
      ENV: docker
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs
  parhelion_db:
    image: postgres:latest
    container_name: parhelion_db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    env_file: .env
      # The host is always `localhost` and the port is always `5432`. The POSTGRES_HOST
      # and POSTGRES_PORT variables in the .env file are ignored.
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data

volumes:
  db_data:
